#############################################################################
# Makefile for building: navie
# Generated by qmake (3.1) (Qt 5.11.2)
# Project:  navie.pro
# Template: app
# Command: /home/alastrim/Soft/Qt/5.11.2/gcc_64/bin/qmake -o Makefile navie.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_QML_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -llaspack -lxc -g -W -Wall -Wunused -Wcast-align -Werror -pedantic -pedantic-errors -fstack-protector-all -Wfloat-equal -Wpointer-arith -Wwrite-strings -Wcast-align -Wno-long-long -Wmissing-declarations -O2 -ffast-math -lm -std=c++14 -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../../Soft/Qt/5.11.2/gcc_64/include -I../../Soft/Qt/5.11.2/gcc_64/include/QtGui -I../../Soft/Qt/5.11.2/gcc_64/include/QtCore -I. -isystem /usr/include/libdrm -I../../Soft/Qt/5.11.2/gcc_64/mkspecs/linux-g++
QMAKE         = /home/alastrim/Soft/Qt/5.11.2/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/alastrim/Soft/Qt/5.11.2/gcc_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/alastrim/Soft/Qt/5.11.2/gcc_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = navie1.0.0
DISTDIR = /home/alastrim/Al/NewPopov/.tmp/navie1.0.0
LINK          = g++
LFLAGS        = -llaspack -lxc -Wl,-rpath,/home/alastrim/Soft/Qt/5.11.2/gcc_64/lib
LIBS          = $(SUBLIBS) -llaspack -lxc -L/home/alastrim/Soft/Qt/5.11.2/gcc_64/lib -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		misc.cpp \
		printers.cpp \
		grid.cpp \
		matvec.cpp \
		discrete_function.cpp \
		loop.cpp \
		fillers_misc.cpp \
		fillers_matrix.cpp \
		fillers_functions.cpp 
OBJECTS       = main.o \
		misc.o \
		printers.o \
		grid.o \
		matvec.o \
		discrete_function.o \
		loop.o \
		fillers_misc.o \
		fillers_matrix.o \
		fillers_functions.o
DIST          = ../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/spec_pre.prf \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/common/unix.conf \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/common/linux.conf \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/common/sanitize.conf \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/common/gcc-base.conf \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/common/g++-base.conf \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/common/g++-unix.conf \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/qconfig.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/qt_functions.prf \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/qt_config.prf \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/toolchain.prf \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/default_pre.prf \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/resolve_config.prf \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/default_post.prf \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/qml_debug.prf \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/warn_on.prf \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/qt.prf \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/resources.prf \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/moc.prf \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/unix/opengl.prf \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/unix/thread.prf \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/qmake_use.prf \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/file_copies.prf \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/testcase_targets.prf \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/exceptions.prf \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/yacc.prf \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/lex.prf \
		navie.pro misc.h \
		printers.h \
		grid.h \
		matvec.h \
		discrete_function.h \
		fillers_misc.h \
		fillers_matrix.h \
		fillers_functions.h \
		loop.h main.cpp \
		misc.cpp \
		printers.cpp \
		grid.cpp \
		matvec.cpp \
		discrete_function.cpp \
		loop.cpp \
		fillers_misc.cpp \
		fillers_matrix.cpp \
		fillers_functions.cpp
QMAKE_TARGET  = navie
DESTDIR       = 
TARGET        = navie


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: navie.pro ../../Soft/Qt/5.11.2/gcc_64/mkspecs/linux-g++/qmake.conf ../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/spec_pre.prf \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/common/unix.conf \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/common/linux.conf \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/common/sanitize.conf \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/common/gcc-base.conf \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/common/g++-base.conf \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/common/g++-unix.conf \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/qconfig.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/qt_functions.prf \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/qt_config.prf \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/toolchain.prf \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/default_pre.prf \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/resolve_config.prf \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/default_post.prf \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/qml_debug.prf \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/warn_on.prf \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/qt.prf \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/resources.prf \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/moc.prf \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/unix/opengl.prf \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/unix/thread.prf \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/qmake_use.prf \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/file_copies.prf \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/testcase_targets.prf \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/exceptions.prf \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/yacc.prf \
		../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/lex.prf \
		navie.pro \
		../../Soft/Qt/5.11.2/gcc_64/lib/libQt5Gui.prl \
		../../Soft/Qt/5.11.2/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -o Makefile navie.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/spec_pre.prf:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/common/unix.conf:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/common/linux.conf:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/common/sanitize.conf:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/common/gcc-base.conf:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/common/g++-base.conf:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/common/g++-unix.conf:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/qconfig.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3danimation.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_charts.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_charts_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_location.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_networkauth.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_purchasing.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_repparser.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_webview.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/qt_functions.prf:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/qt_config.prf:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/linux-g++/qmake.conf:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/exclusive_builds.prf:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/toolchain.prf:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/default_pre.prf:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/resolve_config.prf:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/default_post.prf:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/qml_debug.prf:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/warn_on.prf:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/qt.prf:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/resources.prf:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/moc.prf:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/unix/opengl.prf:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/unix/thread.prf:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/qmake_use.prf:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/file_copies.prf:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/testcase_targets.prf:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/exceptions.prf:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/yacc.prf:
../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/lex.prf:
navie.pro:
../../Soft/Qt/5.11.2/gcc_64/lib/libQt5Gui.prl:
../../Soft/Qt/5.11.2/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile navie.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents misc.h printers.h grid.h matvec.h discrete_function.h fillers_misc.h fillers_matrix.h fillers_functions.h loop.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp misc.cpp printers.cpp grid.cpp matvec.cpp discrete_function.cpp loop.cpp fillers_misc.cpp fillers_matrix.cpp fillers_functions.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/data/dummy.cpp
	g++ -pipe -llaspack -lxc -g -W -Wall -Wunused -Wcast-align -Werror -pedantic -pedantic-errors -fstack-protector-all -Wfloat-equal -Wpointer-arith -Wwrite-strings -Wcast-align -Wno-long-long -Wmissing-declarations -O2 -ffast-math -lm -std=c++14 -g -Wall -W -dM -E -o moc_predefs.h ../../Soft/Qt/5.11.2/gcc_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean 

####### Compile

main.o: main.cpp misc.h \
		grid.h \
		discrete_function.h \
		printers.h \
		fillers_misc.h \
		fillers_matrix.h \
		fillers_functions.h \
		loop.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

misc.o: misc.cpp misc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o misc.o misc.cpp

printers.o: printers.cpp printers.h \
		misc.h \
		discrete_function.h \
		grid.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o printers.o printers.cpp

grid.o: grid.cpp grid.h \
		misc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o grid.o grid.cpp

matvec.o: matvec.cpp matvec.h \
		misc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o matvec.o matvec.cpp

discrete_function.o: discrete_function.cpp discrete_function.h \
		misc.h \
		grid.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o discrete_function.o discrete_function.cpp

loop.o: loop.cpp loop.h \
		misc.h \
		discrete_function.h \
		grid.h \
		matvec.h \
		fillers_misc.h \
		fillers_matrix.h \
		fillers_functions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o loop.o loop.cpp

fillers_misc.o: fillers_misc.cpp fillers_misc.h \
		misc.h \
		fillers_matrix.h \
		fillers_functions.h \
		matvec.h \
		discrete_function.h \
		grid.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fillers_misc.o fillers_misc.cpp

fillers_matrix.o: fillers_matrix.cpp fillers_misc.h \
		misc.h \
		fillers_matrix.h \
		fillers_functions.h \
		matvec.h \
		discrete_function.h \
		grid.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fillers_matrix.o fillers_matrix.cpp

fillers_functions.o: fillers_functions.cpp fillers_misc.h \
		misc.h \
		fillers_matrix.h \
		fillers_functions.h \
		matvec.h \
		discrete_function.h \
		grid.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fillers_functions.o fillers_functions.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

